core/urls.py
from django.urls import path, include
from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
]

district_reporting/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('agriculture/', include('agriculture.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('report/', include('report.urls')),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from dashboard.models import Sector, Department


class UserProfile(models.Model):
    SECTOR = 1
    DISTRICT = 2
    SUPER = 3
    ROLE_CHOICES = (
        (SECTOR, 'Sector Level User'),
        (DISTRICT, 'District Level User'),
        (SUPER, 'Super Level User'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    sector = models.ForeignKey(Sector, on_delete=models.CASCADE, related_name='sector_profiles')
    department = models.ForeignKey(Department, on_delete=models.CASCADE, blank=True, null=True, related_name='user_department')
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, default=1)

    class Meta:
        verbose_name = "User Profile"
        verbose_name_plural = "User Profiles"

    def __str__(self):
        return self.user.get_username()

dashboard/models.py
from django.db import models
import datetime
from django.core.validators import MaxValueValidator, MinValueValidator

ICYICIRO = (
    ('', 'Choose...'),
    ('one', '1'),
    ('two', '2'),
    ('three', '3')
)

def current_year():
    return datetime.date.today().year


def max_value_current_year(value):
    return MaxValueValidator(current_year())(value)


class District(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        verbose_name = "District"
        verbose_name_plural = "Districts"

    def __str__(self):
        return self.name


class Sector(models.Model):
    name = models.CharField(max_length=200)
    district = models.ForeignKey(District, on_delete=models.CASCADE, related_name='district_sectors')

    class Meta:
        verbose_name = "Sector"
        verbose_name_plural = "Sectors"

    def __str__(self):
        return self.name

###################################

class Department(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        verbose_name='Department'
        verbose_name_plural = 'Departments'

    def __str__(self):
        return self.name


class Cell(models.Model):
    name = models.CharField(max_length=200)
    sector = models.ForeignKey(Sector, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Cell'
        verbose_name_plural = 'Cells'

    def __str__(self):
        return self.name


class Village(models.Model):
    name = models.CharField(max_length=200)
    cell = models.ForeignKey(Cell, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Village'
        verbose_name_plural = 'Villages'

    def __str__(self):
        return self.name


class KPI(models.Model):
    name = models.CharField(max_length=200)


    class Meta:
        verbose_name = "KPI"
        verbose_name_plural = "KPIs"

    def __str__(self):
        return self.name


class Umuryango(models.Model):
    PENDING = 0
    ACHIEVED = 1
    R_CHOICES = (
        (PENDING, 0), (ACHIEVED, 1))

    TARGET = 1
    R1_CHOICES = ((TARGET, 1), (TARGET, 1))

    ONE = 1
    TWO = 2
    THREE = 3
    FOUR = 4
    IKICIRO = ((ONE, 1), (TWO, 2), (THREE, 3), (FOUR, 4))

    name = models.CharField(max_length=200)
    number_of_member = models.PositiveIntegerField()
    icyiciro = models.PositiveIntegerField(choices=IKICIRO)
    irangamuntu = models.BigIntegerField()
    kpi = models.ForeignKey(KPI, on_delete=models.CASCADE, default=None, related_name='kpi_name')
    target = models.PositiveSmallIntegerField(choices=R1_CHOICES, default=1)
    achieved = models.PositiveSmallIntegerField(choices=R_CHOICES, default=0)
    sector = models.ForeignKey(Sector, on_delete=models.CASCADE)
    cell = models.ForeignKey(Cell, on_delete=models.CASCADE)
    village = models.ForeignKey(Village, on_delete=models.CASCADE, related_name='village_cell')


    def __str__(self):
        return self.name

templates/umuryango/add_data_form.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
<div class="card">
  <div class="card-header" style="background-color:#796AEE;">
    {% with url_name=request.resolver_match.url_name  %}
              {% if url_name == 'family' %}
                 <h6 class="text-white">Add Family</h6>
                {% elif url_name == 'add_kpi' %}
                  <h6 class="text-white">Add KPI</h6>
              {% endif %}
      {% endwith %}
  </div>
  <div class="card-body">
    <form method="post" id="personForm" data-cells-url="{% url 'ajax_load_cells' %}" data-village-url="{% url 'ajax_load_villages' %}" novalidate enctype="multipart/form-data">
       {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>
</div>

{##############    scripts for loading cells based on sector ##############}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_sector").change(function () {
      var url = $("#personForm").attr("data-cells-url");
      var sectorId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'sector': sectorId
        },
        success: function (data) {
          $("#id_cell").html(data);
        }
      });
    });
 </script>


{##############    scripts for loading village based on cell ##############}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_cell").change(function () {
      var url = $("#personForm").attr("data-village-url");
      var cellId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'cell': cellId
        },
        success: function (data) {
          $("#id_village").html(data);
        }
      });
    });
 </script>


{% endblock %}

templates/umuryango/ibyakozwe.html
{% extends '_base.html' %}
{% block content %}

 {% with url_name=request.resolver_match.url_name  %}

  <!----------------  snippets for ibyakozwe in in district and super_level   --------------->

      {% if url_name == 'ibyakozwe' %}
         <div class="container">
            <table class="table table-bordered mb-0">
              <thead class="thead-light">
                <tr>
                  <th>AMAZINA</th>
                  <th>ABAGIZE UMURYANGO</th>
                  <th>IRANGAMUNTU</th>
                  <th>UMURENGE</th>
                  <th>AKAGALI</th>
                  <th>UMUDUGUDU</th>
                  <th>KPI Name</th>
{#                  <th>Change Status</th>#}
                </tr>
              </thead>
              <tbody>
                {% for i in ibyakozwe %}

                    <tr>
                      <td class="align-middle ">{{ i.name }} </td>
                      <td class="align-middle">{{ i.number_of_member }}</td>
                      <td class="align-middle">{{ i.irangamuntu }} </td>
                      <td class="align-middle">{{ i.sector }} </td>
                      <td class="align-middle">{{ i.cell }} </td>
                      <td class="align-middle">{{ i.village }} </td>
                      <td class="align-middle">{{ i.kpi }} </td>
{#                      <td class="align-middle"><a href="{% url 'status' i.id %}" class="btn btn-outline-success btn-sm">Change</a> </td>#}
                    </tr>
                    {% empty %}
                    <tr>
                      <td class="text-center font-italic" colspan="7">No Information Provided Yet</td>
                    </tr>
                {% endfor %}
              </tbody>
            </table><br>
         </div>


    <!-----------------snippets for ibitarakorwa in district and super_level --------->


      {% elif url_name == 'ibisigaye' %}
        <div class="container">
            <table class="table table-bordered mb-0">
              <thead class="thead-light">
                <tr>
                  <th>AMAZINA</th>
                  <th>ABAGIZE UMURYANGO</th>
                  <th>IRANGAMUNTU</th>
                  <th>UMURENGE</th>
                  <th>AKAGALI</th>
                  <th>UMUDUGUDU</th>
                  <th>KPI Name</th>
{#                  <th>Change Status</th>#}
                </tr>
              </thead>
              <tbody>
                {% for i in ibisigaye %}

                    <tr>
                      <td class="align-middle ">{{ i.name }} </td>
                      <td class="align-middle">{{ i.number_of_member }}</td>
                      <td class="align-middle">{{ i.irangamuntu }} </td>
                      <td class="align-middle">{{ i.sector }} </td>
                      <td class="align-middle">{{ i.cell }} </td>
                      <td class="align-middle">{{ i.village }} </td>
                      <td class="align-middle">{{ i.kpi }} </td>
{#                      <td class="align-middle"><a href="{% url 'status' i.id %}" class="btn btn-outline-success btn-sm">Change</a> </td>#}
                    </tr>
                    {% empty %}
                    <tr>
                      <td class="text-center font-italic" colspan="7">No Information Provided Yet</td>
                    </tr>
                {% endfor %}
              </tbody>
            </table>
         </div>


   <!-----------------snippets for ibyakozwe in each sector --------->

    {% elif url_name == 'ibyakozwe_sector' %}
         <div class="container">
            <table class="table table-bordered mb-0">
              <thead class="thead-light">
                <tr>
                  <th>AMAZINA</th>
                  <th>ABAGIZE UMURYANGO</th>
                  <th>IRANGAMUNTU</th>
                  <th>UMURENGE</th>
                  <th>AKAGALI</th>
                  <th>UMUDUGUDU</th>
                  <th>KPI Name</th>
                </tr>
              </thead>
              <tbody>
                {% for i in ibyakozwe_sector %}

                    <tr>
                      <td class="align-middle ">{{ i.name }} </td>
                      <td class="align-middle">{{ i.number_of_member }}</td>
                      <td class="align-middle">{{ i.irangamuntu }} </td>
                      <td class="align-middle">{{ i.sector }} </td>
                      <td class="align-middle">{{ i.cell }} </td>
                      <td class="align-middle">{{ i.village }} </td>
                      <td class="align-middle">{{ i.kpi }} </td>
                    </tr>
                    {% empty %}
                    <tr>
                      <td class="text-center font-italic" colspan="7">No Information Provided Yet</td>
                    </tr>
                {% endfor %}
              </tbody>
            </table><br>
         </div>


    <!-----------------snippets for ibitarakorwa in each sector --------->


      {% elif url_name == 'ibisigaye_sector' %}
        <div class="container">
            <table class="table table-bordered mb-0">
              <thead class="thead-light">
                <tr>
                  <th>AMAZINA</th>
                  <th>ABAGIZE UMURYANGO</th>
                  <th>IRANGAMUNTU</th>
                  <th>UMURENGE</th>
                  <th>AKAGALI</th>
                  <th>UMUDUGUDU</th>
                  <th>KPI Name</th>
                  <th>Change Status</th>
                </tr>
              </thead>
              <tbody>
                {% for i in ibisigaye_sector %}

                    <tr>
                      <td class="align-middle ">{{ i.name }} </td>
                      <td class="align-middle">{{ i.number_of_member }}</td>
                      <td class="align-middle">{{ i.irangamuntu }} </td>
                      <td class="align-middle">{{ i.sector }} </td>
                      <td class="align-middle">{{ i.cell }} </td>
                      <td class="align-middle">{{ i.village }} </td>
                      <td class="align-middle">{{ i.kpi }} </td>
                      <td class="align-middle"><a href="{% url 'status' i.id %}" class="btn btn-outline-success btn-sm">Change</a> </td>
                    </tr>
                    {% empty %}
                    <tr>
                      <td class="text-center font-italic" colspan="8">No Information Provided Yet</td>
                    </tr>
                {% endfor %}
              </tbody>
            </table>
         </div>

     {%endif%}
 {%endwith%}
 {%endblock%}